spring:
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    database: H2
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database_user;DB_CLOSE_ON_EXIT=FALSE
spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html