CREATE TABLE LK_PROVINCE(
    ID UUID DEFAULT  RANDOM_UUID(),
    CODE VARCHAR (4),
    NAME_EN VARCHAR (100),
    NAME_FR VARCHAR (100),
    PRIMARY KEY (ID)
);

CREATE TABLE APP_USER(
    ID UUID DEFAULT RANDOM_UUID(),
    FIRST_NAME VARCHAR (100),
    LAST_NAME VARCHAR (100),
    PROVINCE_ID UUID,
    PRIMARY KEY (ID),
    FOREIGN KEY (PROVINCE_ID) REFERENCES LK_PROVINCE(ID)
);

INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Alberta', 'Alberta');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('British Columbia', 'Colombie-Britannique');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Manitoba', 'Manitoba');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('New Brunswick', 'Nouveau-Brunswick');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Newfoundland and Labrador', 'Terre-Neuve-et-Labrador');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Northwest Territories', 'Territoires du Nord-Ouest');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Nova Scotia', 'Nouvelle-Écosse');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Nunavut', 'Nunavut');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Ontario', 'Ontario');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Prince Edward Island', 'île-du-Prince-Édouard');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Quebec', 'Québec');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Saskatchewan', 'Saskatchewan');
INSERT INTO LK_PROVINCE (NAME_EN, NAME_FR)
VALUES ('Yukon', 'Yukon');