CREATE TABLE LK_PROVINCE(
    ID UUID DEFAULT  RANDOM_UUID(),
    CODE VARCHAR (4),
    NAME_EN VARCHAR (100),
    NAME_FR VARCHAR (100),
    PRIMARY KEY (ID)
);

CREATE TABLE APP_USER(
    ID UUID DEFAULT RANDOM_UUID(),
    FIRST_NAME VARCHAR (100),
    LAST_NAME VARCHAR (100),
    PROVINCE_ID UUID,
    PRIMARY KEY (ID),
    FOREIGN KEY (PROVINCE_ID) REFERENCES LK_PROVINCE(ID)
);

INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('AB', 'Alberta', 'Alberta');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('BC', 'British Columbia', 'Colombie-Britannique');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('MB', 'Manitoba', 'Manitoba');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('NB', 'New Brunswick', 'Nouveau-Brunswick');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('NL', 'Newfoundland and Labrador', 'Terre-Neuve-et-Labrador');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('NT', 'Northwest Territories', 'Territoires du Nord-Ouest');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('NS', 'Nova Scotia', 'Nouvelle-Écosse');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('NU', 'Nunavut', 'Nunavut');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('ON', 'Ontario', 'Ontario');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('PE', 'Prince Edward Island', 'île-du-Prince-Édouard');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('QC', 'Quebec', 'Québec');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('SK', 'Saskatchewan', 'Saskatchewan');
INSERT INTO LK_PROVINCE (CODE, NAME_EN, NAME_FR)
VALUES ('YT', 'Yukon', 'Yukon');